var config = {
	"services": {
		"basemap":"http://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/World_Dark_Gray_Base_Beta/MapServer",
		"cities" :"http://services.arcgis.com/6DIQcwlPy8knb6sg/arcgis/rest/services/HeatIndex_WM_4/FeatureServer/0"
	},
	"baselineYear":"2010",
	"fieldDescriptions": [
	 	{"field" : "AvgSummer_HI", "descShort": "Avg summer heat index", "descLong" : "Average summertime heat index"},
	 	{"field" : "AvgSummer_Temp", "descShort" : "Avg summer temp", "descLong" : "Average summertime temperature"},
	 	{"field" : "AvgSummer_RH", "descShort" : "Avg summer rel humidity", "descLong" : "Average summertime relative humidity"},
	 	{"field" : "HtIdxCaut", "descShort": "Caution days",  "descLong" : "Number of 'caution' days"},
	 	{"field" : "HtIdxECaut", "descShort": "Extreme caution days", "descLong" : "Number of 'extreme caution' days"},
	 	{"field" : "HtIdxDanger", "descShort": "Danger days", "descLong" : "Number of 'danger' days"},
	 	{"field" : "HtIdxEDanger", "descShort": "Extreme danger days", "descLong" : "Number of 'extreme danger' days"},
	 	{"field" : "ConsecHtIdxCaut", "descShort": "Caution days in a row", "descLong" : "Max consecutive 'caution' days"},
	 	{"field" : "ConsecHtIdxECaut", "descShort": "Extreme caution days in a row", "descLong" : "Max consecutive 'extreme caution' days"},
	 	{"field" : "ConsecHtIdxDanger", "descShort": "Danger days in a row", "descLong" : "Max consecutive 'danger' days"},
	 	{"field" : "ConsecHtIdxEDanger", "descShort": "Extreme danger days in a row", "descLong" : "Max consecutive 'extreme danger' days"}
	],
	"fieldmap": [
	{"label"	: "2010",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger"}
	 ]},
	{"label"	: "2020",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_1"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_1"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_1"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_1"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_1"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_1"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_1"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_1"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_1"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_1"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_1"}
	 ]},
	{"label"	: "2030",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12"}
	 ]},
	{"label"	: "2040",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12_13"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12_13"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12_13"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12_13"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12_13"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12_13"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12_13"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12_13"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12_13"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12_13"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12_13"}
	 ]},
	{"label"	: "2050",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12_13_14"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12_13_14"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12_13_14"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12_13_14"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12_13_14"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12_13_14"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12_13_14"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12_13_14"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12_13_14"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12_13_14"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12_13_14"}
	 ]},
	{"label"	: "2060",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12_13_14_15"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12_13_14_15"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12_13_14_15"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12_13_14_15"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12_13_14_15"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12_13_14_15"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12_13_14_15"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12_13_14_15"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12_13_14_15"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12_13_14_15"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12_13_14_15"}
	 ]},
	{"label"	: "2070",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12_13_14_15_16"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12_13_14_15_16"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12_13_14_15_16"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12_13_14_15_16"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12_13_14_15_16"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12_13_14_15_16"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12_13_14_15_16"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12_13_14_15_16"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12_13_14_15_16"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12_13_14_15_1"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12_13_14_15_"}
	 ]},
	{"label"	: "2080",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12_13_14_15_16_17"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12_13_14_15_16_1"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12_13_14_15_16_17"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12_13_14_15_16_17"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12_13_14_15_16_17"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12_13_14_15_16_17"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12_13_14_15_16_17"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12_13_14_15_16_"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12_13_14_15_16_17"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12_13_14_15_2"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12_13_14_151"}
	 ]},
	{"label"	: "2090",
	 "fields"	: [
	 	// {"field" : "AvgJJA_HI", "fieldname" : "AvgJJA_HI"},
	 	{"field" : "AvgSummer_HI", "fieldname" : "AvgSummer_HI_12_13_14_15_16_17_"},
	 	{"field" : "AvgSummer_Temp", "fieldname" : "AvgSummer_Temp_12_13_14_15_16_2"},
	 	{"field" : "AvgSummer_RH", "fieldname" : "AvgSummer_RH_12_13_14_15_16_17_"},
	 	{"field" : "HtIdxCaut", "fieldname" : "HtIdxCaut_12_13_14_15_16_17_18"},
	 	{"field" : "HtIdxECaut", "fieldname" : "HtIdxECaut_12_13_14_15_16_17_18"},
	 	{"field" : "HtIdxDanger", "fieldname" : "HtIdxDanger_12_13_14_15_16_17_1"},
	 	{"field" : "HtIdxEDanger", "fieldname" : "HtIdxEDanger_12_13_14_15_16_17_"},
	 	{"field" : "ConsecHtIdxCaut", "fieldname" : "ConsecHtIdxCaut_12_13_14_15_161"},
	 	{"field" : "ConsecHtIdxECaut", "fieldname" : "ConsecHtIdxECaut_12_13_14_15_18"},
	 	{"field" : "ConsecHtIdxDanger", "fieldname" : "ConsecHtIdxDanger_12_13_14_15_3"},
	 	{"field" : "ConsecHtIdxEDanger", "fieldname" : "ConsecHtIdxEDanger_12_13_14_152"}
	 ]}
	]
};
